# -*- coding: utf-8 -*-
"""01_kajita_preview_control.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a-bO7nTz2PFaRzbOpjXOX8fjwdqDhwqa
"""

#!pip install control
import numpy as np
import control
import matplotlib.pyplot as plt
np.float_ = np.float64

# Parametros

dist_y = 0.12
dist_x = 0.2
n_step = 10
step_pos =np.array([[0.0, 0.0]])
sinal = 1
for i in range(n_step):

    if i==0:

      disty=dist_y/2
    else:
      sinal=-1*sinal
      disty = dist_y

    new_pos = np.array([[step_pos[i][0] + dist_x, step_pos[i][1] + sinal*disty]])
    step_pos = np.vstack((step_pos, new_pos))





zc = 0.814
g = 9.81
dt = 0.01
t_step = 1



t_sim = n_step*t_step - t_step - dt

Nss = int(t_step/dt)
K_sim = int(t_sim/dt)

# trajetoria ZMP
ZMP_x_ref = []
ZMP_y_ref = []
i = 0
for t in  np.arange(0, n_step*t_step, dt):
    ZMP_x_ref.append(step_pos[i,0])
    ZMP_y_ref.append(step_pos[i,1])

    if (t != 0) and (t%t_step < 1e-6):
        i += 1

# equação 13 Kajita

A = np.asmatrix(([1, dt, dt**2/2],
            [0, 1, dt],
            [0, 0, 1]))

B = np.asmatrix((dt**3/6, dt**2/2, dt)).T

C = np.asmatrix((1, 0, -zc/g))

# parametros equação 14 Kajita

Qc = 1
Qx = 0
R = 1e-6

# Criando as matrizes, vetores e variaveis

ux = np.asmatrix(np.zeros((K_sim, 1)))
uy = np.asmatrix(np.zeros((K_sim, 1)))

COM_x = np.asmatrix(np.zeros((3, K_sim+1)))
COM_y = np.asmatrix(np.zeros((3, K_sim+1)))

e_x = np.zeros((K_sim, 1))
e_y = np.zeros((K_sim, 1))

sum_e_x = 0
sum_e_y = 0

COM_x_H = []
COM_y_H = []
ZMP_x_H = []
ZMP_y_H = []
Jerk_x_H = []
Jerk_y_H = []

# Calculo de Gi Gx e Gp
# Design of an optimal controller for a discrete-time system subject to previewable demand by TOHRU KATAYAMA
# https://www.daslhub.org/unlv/wiki/lib/exe/fetch.php?media=yb_thesis:53.pdf acesso em 09/02/2025


CA = C*A
CB = C*B

B_til = np.matrix([[CB[0,0]],
                  [B[0,0]],
                  [B[1,0]],
                  [B[2,0]]])

I_til = np.matrix([[1],
                  [0],
                  [0],
                  [0]])
F_til = np.matrix([[CA[0,0], CA[0,1], CA[0,2]],
                  [A[0,0], A[0,1], A[0,2]],
                  [A[1,0], A[1,1], A[1,2]],
                  [A[2,0], A[2,1], A[2,2]]])

Q_til = np.matrix([[Qc, 0, 0,0],
                  [0, Qx, 0,0],
                  [0, 0,0,0],
                  [0,0,0,0]])

A_til = np.matrix([[1, CA[0,0], CA[0,1], CA[0,2]],
                  [0, A[0,0], A[0,1], A[0,2]],
                  [0, A[1,0], A[1,1], A[1,2]],
                  [0, A[2,0], A[2,1], A[2,2]]])


_ ,K_til, _ = control.dlqr(A_til, B_til, Q_til, R)

Gi =(R + B_til.T*K_til*B_til).I*(B_til.T*K_til*I_til)
Gx =(R + B_til.T*K_til*B_til).I*(B_til.T*K_til*F_til)



Ac_til = A_til - B_til*((R + B_til.T*K_til*B_til).I*(B_til.T*K_til*A_til))


X_til = -Ac_til.T*K_til*I_til

Gp = np.zeros((1,Nss))
Gp[0] = -Gi


for i in range(Nss):
  temp = (R + B_til.T*K_til*B_til).I*(B_til.T)*X_til
  Gp[0,i] = temp[0,0]
  X_til = Ac_til.T*X_til

# --- CONFIGURAÇÕES DO EMPURRÃO (Defina antes do loop for) ---
empurrao = True
k_empurrao1 = 259
k_empurrao2 = 290    # O step exato (instante k) em que o robô sofre o empurrão
pert_accel_x = 0.00       # Intensidade da perturbação de aceleração no eixo X
pert_accel_y = 0.03     # Intensidade da perturbação de aceleração no eixo Y (opcional)

for k in range(K_sim):
      ZMP_x_step = np.asmatrix(ZMP_x_ref[k:k+Nss]).T
      ZMP_y_step = np.asmatrix(ZMP_y_ref[k:k+Nss]).T

      if empurrao and k > k_empurrao1 and k < k_empurrao2:

            COM_x[1, k] += pert_accel_x
            COM_y[1, k] += pert_accel_y

      # equação 13 Kajita p(k) = Cx(k)
      ZMP_x = C*COM_x[:,k]
      ZMP_y = C*COM_y[:,k]

      ZMP_x_H.append(ZMP_x[0,0])
      ZMP_y_H.append(ZMP_y[0,0])

      # calculo de erro
      e_x[k] = ZMP_x - ZMP_x_ref[k]
      e_y[k] = ZMP_y - ZMP_y_ref[k]

      # soma dos erros
      sum_e_x += e_x[k]
      sum_e_y += e_y[k]

      # equação  15 Kajita
      ux[k] = -Gi*sum_e_x - Gx*COM_x[:, k] - Gp*ZMP_x_step
      uy[k] = -Gi*sum_e_y - Gx*COM_y[:, k] - Gp*ZMP_y_step



      Jerk_x_H.append(float(ux[k]))
      Jerk_y_H.append(float(uy[k]))



      COM_x[:,k+1] = A*COM_x[:, k] + B*ux[k]
      COM_y[:,k+1] = A*COM_y[:, k] + B*uy[k]



      COM_x_H.append(COM_x[0,k])
      COM_y_H.append(COM_y[0,k])

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np
from google.colab import files

# ==========================================
# --- CONFIGURAÇÃO DE FONTE PARA O TCC ---
# ==========================================
plt.rcParams.update({
    'font.family': 'serif',            # Força o uso de fontes serifadas (como no LaTeX)
    'mathtext.fontset': 'cm',          # Usa o estilo Computer Modern para matemática
    'font.size': 12,
    'axes.titlesize': 12,              # Títulos ativados
    'axes.labelsize': 12,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'legend.fontsize': 10,
    'figure.figsize': (6.5, 3.5)
})

# ==========================================
# --- PARÂMETROS E VARIÁVEIS DE CONTROLE ---
# ==========================================

# Em que segundo a perturbação começa nesta simulação? (ex: 2.0, 3.5)
t_perturb_start = 2.58

fig_size = (6.5, 3.5)
l_foot = 0.06  # Comprimento do pé em metros
w_foot = 0.04  # Largura do pé em metros

# 1. Transformamos tudo em arrays 1D (achatados)
COM_x_flat = np.array(COM_x_H).flatten()
COM_y_flat = np.array(COM_y_H).flatten()
ZMP_x_flat = np.array(ZMP_x_H).flatten()
ZMP_y_flat = np.array(ZMP_y_H).flatten()
ZMP_x_ref_flat = np.array(ZMP_x_ref).flatten()
ZMP_y_ref_flat = np.array(ZMP_y_ref).flatten()
Jerk_x_flat = np.array(Jerk_x_H).flatten()
Jerk_y_flat = np.array(Jerk_y_H).flatten()
# 2. Descobrimos qual é o menor vetor para alinhar todos eles
N = min(len(COM_x_flat), len(ZMP_x_ref_flat))
time = np.arange(N)/100

# 3. Cortamos todos os vetores para terem exatamente o tamanho N
COM_x_plot = COM_x_flat[:N]
COM_y_plot = COM_y_flat[:N]
ZMP_x_plot = ZMP_x_flat[:N]
ZMP_y_plot = ZMP_y_flat[:N]
zmp_x_ref_plot = ZMP_x_ref_flat[:N]
zmp_y_ref_plot = ZMP_y_ref_flat[:N]
Jerk_x_plot = Jerk_x_flat[:N]
Jerk_y_plot = Jerk_y_flat[:N]
# Função auxiliar para adicionar a seta de perturbação
def add_perturbation_arrow(ax, time_vec, data_vec, t_start):
    # Encontra o índice no vetor de tempo mais próximo do tempo de início
    idx_p = (np.abs(time_vec - t_start)).argmin()

    ax.annotate('',
                 xy=(time_vec[idx_p], data_vec[idx_p]), xycoords='data', # Aponta para o dado
                 xytext=(0, 32), textcoords='offset points', # Texto deslocado para cima
                 fontsize=9, color='red', ha='center',
                 arrowprops=dict(arrowstyle="->", color='red', linewidth=1.3))

# ==========================================
# --- EIXO X (Frontal) ---
# ==========================================
fig1, ax1 = plt.subplots(figsize=fig_size)
ax1.plot(time, COM_x_plot, label="CoM X", color='blue')
ax1.step(time, zmp_x_ref_plot, 'r--', label="ZMP Ref X", where='post')
ax1.plot(time, ZMP_x_plot, 'g', alpha=0.5, label="ZMP Real X")
ax1.set_title("Eixo X (Frontal)")

# Adiciona seta se houver empurrão
if empurrao:
    add_perturbation_arrow(ax1, time, COM_x_plot, t_perturb_start)

ax1.set_xlabel("Tempo [s]")
ax1.set_ylabel("X [m]")
ax1.legend()
ax1.grid(True)
plt.tight_layout()

# ==========================================
# --- EIXO Y (Lateral) ---
# ==========================================
fig2, ax2 = plt.subplots(figsize=fig_size)
ax2.plot(time, COM_y_plot, label="CoM Y", color='blue')
ax2.step(time, zmp_y_ref_plot, 'r--', label="ZMP Ref Y", where='post')
ax2.plot(time, ZMP_y_plot, 'g', alpha=0.5, label="ZMP Real Y")
ax2.set_title("Eixo Y (Lateral)")

# Adiciona seta se houver empurrão
if empurrao:
    add_perturbation_arrow(ax2, time, COM_y_plot, t_perturb_start)

ax2.set_xlabel("Tempo [s]")
ax2.set_ylabel("Y [m]")
ax2.legend()
ax2.grid(True)
plt.tight_layout()



# ==========================================
# --- VISTA SUPERIOR (XY) COM RETÂNGULOS ---
# ==========================================
fig3, ax3 = plt.subplots(figsize=(6.5, 4.5)) # Um pouco mais alta para o grid quadrado
ax3.plot(COM_x_plot, COM_y_plot,'b--', label="CoM", zorder=10)
ax3.plot(ZMP_x_plot, ZMP_y_plot, 'g', alpha=0.5, label="ZMP", zorder=8)

def add_foot_rectangle(ax, x, y, l, w, foot_color):
    rect = patches.Rectangle((x - l/2, y - w/2), l, w,
                             linewidth=1.5, edgecolor=foot_color,
                             facecolor=foot_color, alpha=0.3, zorder=5)
    ax.add_patch(rect)

step_count = 0
for k in range(N):
    if k == 0 or zmp_x_ref_plot[k] != zmp_x_ref_plot[k-1] or zmp_y_ref_plot[k] != zmp_y_ref_plot[k-1]:
        color = 'red' if step_count % 2 == 0 else 'green'
        x_val = float(zmp_x_ref_plot[k])
        y_val = float(zmp_y_ref_plot[k])
        add_foot_rectangle(ax3, x_val, y_val, l_foot, w_foot, color)
        step_count += 1

ax3.set_title("Vista Superior (XY) - Geometria dos Pés")
ax3.set_xlabel("X [m]")
ax3.set_ylabel("Y [m]")
ax3.axis("equal")
ax3.grid(True)
ax3.legend()
plt.tight_layout()



# ==========================================
# --- GRÁFICO DO SINAL DE CONTROLE (JERK) ---
# ==========================================
# Cria uma figura um pouco mais alta com 2 subplots (um embaixo do outro)
fig4, (ax4_x, ax4_y) = plt.subplots(2, 1, figsize=(6.5, 5.0), sharex=True)

# Jerk X
ax4_x.plot(time, Jerk_x_plot, color='purple', label="Jerk X")
ax4_x.set_title("Sinal de Controle (Jerk) - Eixo X")
ax4_x.set_ylabel("Jerk [$m/s^3$]")
ax4_x.grid(True)
ax4_x.legend()
if empurrao:
    add_perturbation_arrow(ax4_x, time, Jerk_x_plot, t_perturb_start)

# Jerk Y
ax4_y.plot(time, Jerk_y_plot, color='orange', label="Jerk Y")
ax4_y.set_title("Sinal de Controle (Jerk) - Eixo Y")
ax4_y.set_xlabel("Tempo [s]")
ax4_y.set_ylabel("Jerk [$m/s^3$]")
ax4_y.grid(True)
ax4_y.legend()
if empurrao:
    add_perturbation_arrow(ax4_y, time, Jerk_y_plot, t_perturb_start)

plt.tight_layout()


print(f"Gráficos gerados (Empurrão={empurrao}), salvos e baixados com sucesso!")