# -*- coding: utf-8 -*-
"""02_mpc_analitico_passos_fixos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vufZTScGg813IzXRmfClTomFYP3Yt_un
"""

import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import inv
np.float_ = np.float64

# Parametros

dist_y = 0.4
dist_x = 0.2
n_step = 9
step_pos =np.array([[0.0, 0.0]])
sinal = 1
for i in range(n_step):

    if i==0:

      dist_y=0.2
    else:
      sinal=-1*sinal
      dist_y = 0.4

    new_pos = np.array([[step_pos[i][0] + dist_x, step_pos[i][1] + sinal*dist_y]])
    step_pos = np.vstack((step_pos, new_pos))





zc = 0.4
g = 9.81
dt = 0.01
t_step = 1

alpha=1
gamma=1500

t_sim = n_step*t_step - t_step - dt

K_preview = int(t_step/dt)
K_sim = int(t_sim/dt)

N=K_preview

# trajetoria ZMP
ZMP_x_ref = []
ZMP_y_ref = []
i = 0
for t in  np.arange(0, n_step*t_step, dt):
    ZMP_x_ref.append(step_pos[i,0])
    ZMP_y_ref.append(step_pos[i,1])

    if (t != 0) and (t%t_step < 1e-6):
        i += 1

# Matriz A e B

A = np.asmatrix(([1, dt, dt**2/2],
            [0, 1, dt],
            [0, 0, 1]))

B = np.asmatrix((dt**3/6, dt**2/2, dt)).T

C = np.asmatrix((1, 0, -zc/g))

# Criando as matrizes Ps

P_ps = np.zeros((N,3))
P_pu = np.zeros((N,N))
P_vs = np.zeros((N,3))
P_vu = np.zeros((N,N))
P_as = np.zeros((N,3))
P_au = np.zeros((N,N))
P_zs = np.zeros((N,3))
P_zu = np.zeros((N,N))

# Calculo das matrizes Ps

aux = np.zeros((N,1))

# P_ps e P_pu
for j in range (N):
    P_ps[j] = np.array([1, (j+1)*dt, ((j+1)**2 * dt**2)/2])

    aux[j] = (1/6 + (j+1)/2 + ((j+1)**2)/2) * (dt**3)

    for k in range(N):
        if j < k:
            P_pu[j,k] = 0
        else:
            P_pu[j,j-k] = aux[k]

# P_vs e P_vu
for j in range (N):
        P_vs[j] = np.array([0, 1, (j+1)*dt])

        aux[j] = (1/2 + (j+1)) * (dt**2)

        for k in range(N):
            if j < k:
                P_vu[j,k] = 0
            else:
                P_vu[j,j-k] = aux[k]

# P_as e P_au
for j in range (N):
        P_as[j] = np.array([0, 0, 1])

        aux[j] = dt

        for k in range(N):
            if j < k:
                P_au[j,k] = 0
            else:
                P_au[j,j-k] = aux[k]

# P_zs e P_zu
for j in range (N):
    P_zs[j] = np.array([1, (j+1)*dt, (((j+1)**2) * (dt**2))/2 - zc/g])

    aux[j] = (((1 + 3*(j) + 3*(j)**2)*(dt**3))/6) - ((zc*dt)/g)

    for k in range(N):
        if j < k:
            P_zu[j,k] = 0
        else:
            P_zu[j,j-k] = aux[k]

# Criando x e y

COM_x = np.asmatrix(np.zeros((3, K_sim+1)))
COM_y = np.asmatrix(np.zeros((3, K_sim+1)))
ux = np.asmatrix(np.zeros((K_sim, 1)))
uy = np.asmatrix(np.zeros((K_sim, 1)))


COM_x_H = []
COM_y_H = []
ZMP_x_H = []
ZMP_y_H = []


# formula (20)(21)
Z_xref = np.zeros((N,1))
Z_yref = np.zeros((N,1))

for i in range(N):
    Z_xref[i] = i*0.2
    Z_yref[i] = 0.2 if i%2==1 else -0.2


inv_term = inv((P_zu.T @ P_zu) + (alpha/gamma)*np.eye(N))@P_zu.T

for k in range(K_sim-1):

    ZMP_x_step = np.asmatrix(ZMP_x_ref[k:k+K_preview]).T
    ZMP_y_step = np.asmatrix(ZMP_y_ref[k:k+K_preview]).T

    X3 =  inv_term*(ZMP_x_step - P_zs * COM_x[:,k])
    Y3 =  inv_term*(ZMP_y_step - P_zs * COM_y[:,k])

    ux[k]=X3[0]
    uy[k]=Y3[0]

    COM_x[:,k+1] = A*COM_x[:,k] + B*ux[k]
    COM_y[:,k+1] = A*COM_y[:,k] + B*uy[k]
    COM_x_H.append(COM_x[0,k])
    COM_y_H.append(COM_y[0,k])

plt.figure()
plt.subplot(3,1,1)
plt.plot(ZMP_x_ref, 'g--', label='ZMP_x_ref')
plt.plot(COM_x_H, 'r--', label='COM_x')
plt.legend()
plt.subplot(3,1,2)
plt.plot(ZMP_y_ref, 'g--', label='ZMP_y_ref')
plt.plot(COM_y_H, 'r--', label='COM_y')
plt.legend()
plt.subplot(3,1,3)
plt.plot(ZMP_x_ref, ZMP_y_ref, 'g--', label='ZMP_ref')
plt.plot(COM_x_H, COM_y_H, 'r--', label='COM')
plt.legend()