# -*- coding: utf-8 -*-
"""04_mpc_passos_automaticos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yS0DtdcR12er9HpEwqtePXbARb36wD3W
"""

import numpy as np
import matplotlib.pyplot as plt
from cvxopt import matrix, solvers

solvers.options['show_progress'] = False

# --- PARÂMETROS ---
Ts = 0.1
Tsim = 10.0
kend = int(Tsim / Ts)
X_dot_ref = 0.2
Y_dot_ref = 0.0
Y_dist = 0.12
h_com = 0.814
theta=0.0
g = 9.81
l_foot = 0.06
w_foot = 0.04
N = 50
Nss = 10
Nf = int(N / Nss)

alpha = 1e-6 # Jerk
beta = 1.0  # Velocity
gamma = 100 # ZMP

# --- MATRIZES A e B ---
A = np.matrix([[1, Ts, Ts**2/2],[0, 1, Ts],[0, 0, 1]])

B = np.matrix([[Ts**3/6],[Ts**2/2],[Ts]])

C = np.asmatrix((1, 0, -h_com/g))

# --- MATRIZES HERDT ---
Pps = np.zeros((N, 3))
Pvs = np.zeros((N, 3))
Pas = np.zeros((N, 3))
Pzs = np.zeros((N, 3))

Ppu = np.zeros((N, N))
Pvu = np.zeros((N, N))
Pau = np.zeros((N, N))
Pzu = np.zeros((N, N))

for i in range(N):
    k_step = i + 1
    Pps[i, :] = [1, k_step*Ts, (k_step**2 * Ts**2)/2]
    Pvs[i, :] = [0, 1, k_step*Ts]
    Pas[i, :] = [0, 0, 1]
    Pzs[i, :] = [1, k_step*Ts, (k_step**2 * Ts**2)/2 - h_com/g]

    for j in range(N):
        if i >= j:
          diff = i - j
          Ppu[i, j] = (1 + 3*diff + 3*diff**2) * (Ts**3 / 6)
          Pvu[i, j] = (1 + 2*diff) * (Ts**2 / 2)
          Pau[i, j] = Ts
          Pzu[i, j] = (1 + 3*diff + 3*diff**2) * (Ts**3 / 6) - (h_com * Ts / g)

# --- FUNÇÕES AUXILIARES ---

def get_U_Uc(N, Nss, kl, Nf):
   Uk_c = np.zeros((N, 1))
   Uk = np.zeros((N, Nf))
   rem_ss = Nss - kl
   for i in range(1, N + 1):
      if i <= rem_ss:
          Uk_c[i-1, 0] = 1
      else:
        foot_idx = int(np.ceil((i - rem_ss) / Nss))
        if foot_idx <= Nf:
          Uk[i-1, foot_idx-1] = 1
        else:
          Uk[i-1, Nf-1] = 1
   return np.matrix(Uk), np.matrix(Uk_c)



def create_Gcoll(Nf):
    size = Nf + 1
    Gcoll = np.zeros((size, size))
    for i in range(size):
        if i == 0:
            Gcoll[i, 0] = 1
        else:

            sign = (-1)**(i)
            Gcoll[i, i] = 1 * sign
            Gcoll[i, i-1] = -1 * sign
    return Gcoll

# --- INICIALIZAÇÃO DA SIMULAÇÃO ---
x_CoM = np.zeros((3, kend))
y_CoM = np.zeros((3, kend))
Xf_log = []
Yf_log = []
ZMPX_real = []
ZMPY_real = []
kl = 0
Xk_fc = 0.0
Yk_fc = Y_dist / 2.0
y_CoM[0, 0] = Yk_fc
feet = 0
Gcoll = create_Gcoll(Nf)

# Matrizes para restrições
Dsx_single = np.matrix([[1.0], [-1.0]])
Dsx = np.kron(np.eye(N), Dsx_single)
Ys = 0
s_feet = np.matrix([[l_foot/2], [l_foot/2]])
w_feet = np.matrix([[w_foot/2], [w_foot/2]])

A_acc_ineq = np.vstack([Pau, -Pau])
A_acc_total = np.hstack([A_acc_ineq, np.zeros((2*N, Nf))])

# --- CONFIGURAÇÕES DO EMPURRÃO (Defina antes do loop for) ---
empurrao = True
k_empurrao1 = 25
k_empurrao2 = 29     # O step exato (instante k) em que o robô sofre o empurrão
pert_accel_x = -0.09      # Intensidade da perturbação de aceleração no eixo X
pert_accel_y = 0.0     # Intensidade da perturbação de aceleração no eixo Y (opcional)

for k in range(kend-1):
    xk_CoM = x_CoM[:, k].reshape(3, 1)
    yk_CoM = y_CoM[:, k].reshape(3, 1)



    # Obter matrizes variantes no tempo
    Uk, Uk_c = get_U_Uc(N, Nss, kl, Nf)

    # Construir QP (H e f)
    H11 = alpha*np.eye(N) + beta*(Pvu.T @ Pvu) + gamma*(Pzu.T @ Pzu)
    H12 = -gamma*(Pzu.T @ Uk)
    H21 = H12.T
    H22 = gamma*(Uk.T @ Uk)

    epsilon = 1e-9
    Hqp = matrix(np.block([[H11, H12], [H21, H22]]) + np.eye(N + Nf) * epsilon)

    # fqp
    f1 = beta * Pvu.T @ (Pvs @ xk_CoM - X_dot_ref) + gamma * Pzu.T @ (Pzs @ xk_CoM - Uk_c * Xk_fc)
    f2 = -gamma * Uk.T @ (Pzs @ xk_CoM - Uk_c * Xk_fc)
    fqp = matrix(np.vstack([f1, f2]))

    # Restrições ZMP
    A_zmp = np.hstack([Dsx @ Pzu, -Dsx @ Uk])
    b_zmp = np.tile(s_feet, (N, 1)) + Dsx @ (Uk_c * Xk_fc) - Dsx @ (Pzs @ xk_CoM)

    # Restrições Aceleração
    b_acc = np.vstack([np.ones((N,1)) - Pas@xk_CoM,np.ones((N,1)) + Pas@xk_CoM])

    A_total = matrix(np.vstack([A_acc_total, A_zmp]))
    b_total = matrix(np.vstack([b_acc, b_zmp]))
    # 4. Resolver
    sol_x = solvers.qp(Hqp, fqp, A_total, b_total)
    u_x = sol_x['x'][0]

    # 5. Evoluir Dinâmica
    x_CoM[:, k+1] = (A @ xk_CoM + B * u_x).flatten()

    # Log ZMP Real

    Xf_log.append(Xk_fc)

    # -----------------------------------------------------------------------------------------------------------------------------------
    # logica em Y

    # fqp
    fa = beta*Pvu.T @ (Pvs @ yk_CoM - Y_dot_ref) + gamma*Pzu.T @ (Pzs @ yk_CoM - Uk_c*Yk_fc)
    fb = -gamma*Uk.T @ (Pzs @ yk_CoM - Uk_c*Yk_fc)
    fy = matrix(np.vstack([fa,fb]))

    # Restrições ZMP
    A_zmp = np.hstack([Dsx @ Pzu, -Dsx @ Uk])
    b_zmp = np.tile(w_feet, (N, 1)) + Dsx @ (Uk_c*Yk_fc) - Dsx @ (Pzs @ yk_CoM)

    # Restrições Aceleração
    b_acc = np.vstack([np.ones((N,1)) - Pas@yk_CoM,np.ones((N,1)) + Pas@yk_CoM])

    # Restrições feet colision
    Gcoll_f = Gcoll[1:, 1:]

    A_coll_y = np.hstack([np.zeros((Nf, N)), ((-1)**feet) * Gcoll_f  ])
    dc_x = -np.sin(theta)
    dc_y = np.cos(theta)
    b_coll_y = -np.ones((Nf, 1)) * Y_dist

    if (Y_dot_ref>=0 and feet == 1):
      b_coll_y[0, 0] -= ((-1)**feet) * (dc_x * Xk_fc + dc_y * Yk_fc)
    else:
      if (Y_dot_ref<0 and feet == 0):
        b_coll_y[0, 0] -= ((-1)**feet) * (dc_x * Xk_fc + dc_y * Yk_fc)

    A_total_y = matrix(np.vstack([A_acc_total, A_zmp, A_coll_y]))
    b_total_y = matrix(np.vstack([b_acc, b_zmp, b_coll_y]))

    sol_y = solvers.qp(Hqp, fy, A_total_y, b_total_y)
    u_y = sol_y['x'][0]

    # 5. Evoluir Dinâmica
    y_CoM[:, k+1] = (A @ yk_CoM + B * u_y).flatten()


    Yf_log.append(Yk_fc)

    x_next = A @ xk_CoM + B * u_x
    y_next = A @ yk_CoM + B * u_y

    # O empurrão altera a aceleração física do robô na transição para o próximo passo
    if empurrao and k > k_empurrao1 and k < k_empurrao2:
        x_CoM[1, k+1] += pert_accel_x
        y_CoM[1, k+1] += pert_accel_y
        print((C@xk_CoM)[0,0])

    ZMPX_real.append((C@xk_CoM)[0,0])
    ZMPY_real.append((C@yk_CoM)[0,0])
    # 6. Lógica de Troca de Pé
    if kl == Nss:
       Xk_fc = sol_x['x'][N]
       Yk_fc = sol_y['x'][N]
       Ys = sol_y['x'][N:]
       kl = 0
       feet = 1 if feet < 1 else 0
    else:
       kl += 1

import matplotlib.pyplot as plt
import matplotlib.patches as patches

# ==========================================
# --- CONFIGURAÇÃO DE FONTE PARA O TCC ---
# ==========================================

plt.rcParams.update({
    'font.family': 'serif',
    'mathtext.fontset': 'cm',
    'font.size': 12,
    'axes.titlesize': 12, # Título do gráfico ativado
    'axes.labelsize': 12,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'legend.fontsize': 10,
    'figure.figsize': (6.5, 3.5)
})

# ==========================================
# --- PARÂMETROS DE CONTROLE E SIMULAÇÃO ---
# ==========================================

prefixo = 'Herdt'

# --- >>> AJUSTE AQUI O TEMPO DE INÍCIO <<< ---
# Em que segundo a perturbação começa? (ex: 2.0s, 4.5s)
t_perturb_start = 2.6

fig_size = (6.5, 3.5)
l_foot = 0.06
w_foot = 0.04

time = np.linspace(0, Tsim, kend)

# Função auxiliar para adicionar a seta de perturbação
def add_perturbation_arrow(ax, time_vec, data_vec, t_start):
    # Encontra o índice no vetor de tempo mais próximo do tempo de início
    idx_p = (np.abs(time_vec - t_start)).argmin()

    ax.annotate('',
                 xy=(time_vec[idx_p], data_vec[idx_p]), xycoords='data', # Aponta para o dado
                 xytext=(0, 32), textcoords='offset points', # Texto deslocado para cima
                 fontsize=9, color='red', ha='center',
                 arrowprops=dict(arrowstyle="->", color='red', linewidth=1.3))


# ==========================================
# --- EIXO X (Frontal) ---
# ==========================================
fig1, ax1 = plt.subplots(figsize=fig_size)
ax1.set_title("Eixo X (Frontal)") # Título de volta
ax1.plot(time, x_CoM[0,:], label="CoM X", color='blue')
ax1.step(time[:-1], Xf_log, 'r--', label="Passo X", where='post')
ax1.plot(time[:-1], ZMPX_real, 'g', alpha=0.5, label="ZMP Real")

# Adiciona seta se houver empurrão
if empurrao:
    add_perturbation_arrow(ax1, time, x_CoM[0,:], t_perturb_start)

ax1.set_xlabel("Tempo [s]")
ax1.set_ylabel("X [m]")
ax1.legend()
ax1.grid(True)
plt.tight_layout()


# ==========================================
# --- EIXO Y (Lateral) ---
# ==========================================
fig2, ax2 = plt.subplots(figsize=fig_size)
ax2.set_title("Eixo Y (Lateral)") # Título de volta
ax2.plot(time, y_CoM[0,:], label="CoM Y", color='blue')
ax2.step(time[:-1], Yf_log, 'r--', label="Passo Y", where='post')
ax2.plot(time[:-1], ZMPY_real, 'g', alpha=0.5, label="ZMP Real")

# Adiciona seta se houver empurrão
if empurrao:
    add_perturbation_arrow(ax2, time, y_CoM[0,:], t_perturb_start)

ax2.set_xlabel("Tempo [s]")
ax2.set_ylabel("Y [m]")
ax2.legend()
ax2.grid(True)
plt.tight_layout()


# ==========================================
# --- VISTA SUPERIOR (XY) COM RETÂNGULOS ---
# ==========================================
fig3, ax3 = plt.subplots(figsize=(6.5, 4.5))
ax3.set_title("Vista Superior (XY) - Geometria dos Pés") # Título de volta
ax3.plot(x_CoM[0,:], y_CoM[0,:], label="CoM", color='blue', zorder=10)

def add_foot_rectangle(ax, x, y, l, w, foot_color):
    rect = patches.Rectangle((x - l/2, y - w/2), l, w,
                             linewidth=1.5, edgecolor=foot_color,
                             facecolor=foot_color, alpha=0.3, zorder=5)
    ax.add_patch(rect)

step_count = 0
for k in range(len(Xf_log)):
    if k == 0 or Xf_log[k] != Xf_log[k-1] or Yf_log[k] != Yf_log[k-1]:
        color = 'red' if step_count % 2 == 0 else 'green'
        add_foot_rectangle(ax3, Xf_log[k], Yf_log[k], l_foot, w_foot, color)
        step_count += 1

ax3.set_xlabel("X [m]")
ax3.set_ylabel("Y [m]")
ax3.axis("equal")
ax3.grid(True)
ax3.legend()
plt.tight_layout()


print(f"Gráficos gerados (Empurrão={empurrao}), com títulos e setas, e baixados com sucesso!")

